SELECT "YEAR", "CITY", l."STATIONID", avg("WASTECOLLECTED") as avg_waste_collected
FROM FACTTRIPS as l
LEFT JOIN DIMSTATION as r
ON l."STATIONID"=r."STATIONID"
LEFT JOIN DIMDATE as d
ON l."DATEID"=d."DATEID"
GROUP BY cube("YEAR", "CITY", l."STATIONID");