SELECT "YEAR", "CITY", l."STATIONID", sum("WASTECOLLECTED") as total_waste_collected
FROM FACTTRIPS as l
LEFT JOIN DIMSTATION as r
ON l."STATIONID"=r."STATIONID"
LEFT JOIN DIMDATE as d
ON l."DATEID"=d."DATEID"
GROUP BY ROLLUP ("YEAR", "CITY", l."STATIONID");